backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

use_large_media_transforms_in_media_library: false

collections:
  - name: "blog"
    label: "Work"
    folder: "src/pages/work"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - label: "Image"
        name: "image"
        widget: "image"
        media_library:
          config:
            multiple: false
      - {label: "Video Type", name: "videoType", widget: "select", options: ["vimeo", "youtube"]}
      - {label: "Video ID", name: "videoId", widget: "string"}
      - {label: "Video Aspect Ratio", name: "ratio", widget: "number", valueType: "float", min: 0, default: 1.778}
      - {label: "Show on Frontpage", name: "isFrontPage", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Credits"
        name: "credits"
        widget: "list"
        fields:
          - {label: "Label", name: "label", widget: "string"}
          - {label: "Text", name: "text", widget: "text"}
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Awards"
        name: "awards"
        widget: "relation"
        collection: "awards"
        searchFields: ["year", "grade", "title", "category"]
        valueField: "slug"
        displayFields: ["year", "grade", "title", "category"]
        multiple: true
        required: false

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Index Page"
        name: "Index Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Awards"
            name: "awards"
            widget: "relation"
            collection: "awards"
            searchFields: ["year", "grade", "title", "category"]
            valueField: "date"
            displayFields: ["year", "grade", "title", "category"]
            multiple: true
          - label: "Selected Clients"
            name: "selectedClients"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Image"
            name: "image"
            widget: "image"
            media_library:
              config:
                multiple: false
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/imprint/index.md"
        label: "Imprint"
        name: "imprint"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "awards"
    label: "Awards"
    folder: "src/pages/awards"
    create: true
    slug: "{{slug}}-{{category}}-{{year}}"
    editor:
      preview: false
    summary: "{{title}} {{category}} {{year}} {{grade}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "award"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Grade", name: "grade", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Link", name: "href", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "date", hint: "only used for ordering, newer comes first"}
      - {label: "Timestamp (do not change!)", name: "timestamp", widget: "date", hint: "used internally for references"}
